### ISSUE TITLE
plot_erp fails if color column doesnt exist

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/UnfoldMakie.jl#353]
**Describe the bug**
if you take a dataframe that doesnt have coefname or color in it, unfoldmakie defaults to nothing, which fails

```julia
plot_erp(zeros(10,10),mapping=(;color=nothing))
```
**Versions:**
 - Julia:1.11.4
 - UnfoldMakie: 0.5.16

**Additional context**

**Comment by vladdez** [comment]
fixed by updating AoG

**Comment by behinger** [comment]
is this fixed? for me it is not with fresh installed UnfoldMakie 0.5.16

I get a similar error if color is an integer

**Comment by behinger** [comment]
this still fails in 0.5.17: `plot_erp(zeros(10,10),mapping=(;color=nothing))` at least for me

**Comment by vladdez** [comment]
It fails indeed, but now (seems so) it is different error:

`Error showing value of type Figure:
ERROR: BoundsError: attempt to access 7-element Vector{RGBA{Float32}} at index [8]`

**Comment by vladdez** [comment]
> It fails indeed, but now (seems so) it is different error:
> 
> `Error showing value of type Figure: ERROR: BoundsError: attempt to access 7-element Vector{RGBA{Float32}} at index [8]`

fixed by 
```
if !haskey(config.visual, :color)  || config.visual.color isa AbstractVector
  config_kwargs!(config; visual = (; colormap = nothing, color = :black))
  @warn """By default we used `black` color for lines. If you need something else, please specify `config.visual.color`."""
end
```

**Comment by behinger** [comment]
why should this throw a warning? not providing color is not a failure, right?

**Comment by vladdez** [comment]
> why should this throw a warning? not providing color is not a failure, right?

this is more nudge/hint then a warning

**Comment by behinger** [comment]
I dont like it, I think we should use warnings only, if the user actually does something that could be wrong

**Comment by behinger** [comment]
mh - I dont know. We dont put infos for all our defaults, do we? that would be a mess..

`|| config.visual.color isa AbstractVector` why is that there?

**Comment by vladdez** [comment]
> mh - I dont know. We dont put infos for all our defaults, do we? that would be a mess..
> 
> `|| config.visual.color isa AbstractVector` why is that there?

- I did it to make a tool more user friendly, little infos can help users
- AbstractVector check is necessary because by default it is `color = Makie.wong_colors()`. If `mapping.color = nothing`, `visual.color` need to be set to single color. Same time we need to give users opportunity to change that color.

**Comment by behinger** [comment]
- I understand why you do it, but I disagree with the path you want to go. If you think that through, with a simple plot_erp(model) there should be tens to hundreds of "infos" or "warnings", each specifying linestyle, color, mapping, axis labels, any default you can think of. If you really want such a mode it should be optional and by default off. But I can imagine that many users will just ignore theses messages and/or be annoyed by them
- I dont understand, what if a user wants Wong_Color? or provide an array for the colors?

**Comment by vladdez** [comment]
- the best option will be to move it somewhere in configs then
- maybe when `mapping.color = nothing` we should prevent any non-solid colormaps?
